# Generated by Django 2.2.4 on 2019-08-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [

    ]

    operations = [
       
    ]
