# Generated by Django 2.2.4 on 2019-08-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BulletGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.BooleanField(default=False)),
                ('pseudoName', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('codes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BulletGroup.Codes')),
            ],
        ),
        migrations.AddField(
            model_name='codes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletGroup.Group'),
        ),
    ]
