# Generated by Django 2.2.4 on 2019-09-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BulletGroup', '0002_auto_20190822_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletGroup.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudoName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
