# Generated by Django 2.2.4 on 2019-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletGroup', '0007_auto_20190918_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
