# Generated by Django 2.2.4 on 2019-09-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletGroup', '0009_auto_20190918_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
